# ============================================
# PREPROCESSING RULES
# ============================================
# Clean and collapse gene presence/absence matrix

rule process_matrix:
    """
    Preprocess gene presence/absence matrix generated by Panaroo.
    """
    input:
        matrix = "results/panaroo/gene_presence_absence.csv"
    output:
        collapsed = "data/interim/collapsed_matrix.csv",
        constant = "data/interim/constant_genes.txt",
        core = "data/interim/core_genes.txt",
        singletons = "data/interim/singletons.txt",
        non_unique_genes = "data/interim/non_unique_genes.csv",
        non_unique_genomes = "data/interim/non_unique_genomes.csv"
    params:
        roary_format = config["preprocessing"]["roary_format"]
    log:
        "logs/preprocessing/process_matrix.log"
    benchmark:
        "benchmarks/preprocessing/process_matrix.tsv"
    conda:
        "../../envs/py.yml"
    script:
        "../scripts/process_matrix.py"
